services:
  backend:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env

  mongo:
    image: mongo:6
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
